# Project information
site_name: epanet-js
site_description: >-
  Run EPANET in your browser with epanet-js — no download needed. Works on Mac, Linux, or Windows. Save files locally. Modern, enhanced, and built on the trusted EPANET engine.
site_author: Luke Butler
site_url: https://epanetjs.com/

# Repository
repo_name: epanet-js
repo_url: https://github.com/modelcreate/epanet-js
edit_uri: blob/master/website/docs/

# Copyright
copyright: Iterating Inc.

# Configuration
theme:
  name: material
  custom_dir: "theme/"
  language: en
  palette:
    primary: epanet
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: "epanetjs-logo"
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
#    - instant

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/modelcreate/epanet-js
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lukepbutler_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lukepbutler/
  analytics:
    provider: google
    property: G-P3DE99YELD

extra_css:
  - stylesheets/colours.css

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work
  - blog
  #  - awesome-pages
#  - minify:
#      minify_html: true

nav:
  - Home: index.html
  - Toolkit:
      - Getting Started: api/index.md
      - Learn More:
          - What is Water Modelling: api/introduction/water-modelling.md
          - Library Development: api/introduction/development.md
          - Examples:
              - index: api/introduction/examples/index.md
              - React + Vite + TypeScript: api/introduction/examples/vite.md
          - Showcase: api/introduction/showcase.md
      - Toolkit Overview: api/toolkit.md
      - Workspace Class: api/workspace.md
      - Project Class: api/project.md
      - Project Class (Methods):
          - Project: api/project-functions/project.md
          - Hydraulic Analysis: api/project-functions/hydraulic-analysis.md
          - Water Quality: api/project-functions/water-quality.md
          - Reporting: api/project-functions/reporting.md
          - Analysis Options: api/project-functions/analysis-options.md
          - Network Node: api/project-functions/network-node.md
          - Nodal Demand: api/project-functions/nodal-demand.md
          - Network Link: api/project-functions/network-link.md
          - Time Pattern: api/project-functions/time-pattern.md
          - Data Curve: api/project-functions/data-curve.md
          - Simple Control: api/project-functions/simple-control.md
          - Rule Based Control: api/project-functions/rule-based-control.md
          - Enumerated Types: api/project-functions/enumerated-types.md
  - Blog:
      - blog/index.md
